### ISSUE TITLE
Broche final

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-VaqueroFontenla#12]
Ole @VaqueroFontenla !!!

Rematamos y le ponemos la guinda?

- Hay que transformar los textos del menú para que sean uppercase.
- Parece que el menú no está totalmente centrado verticalmente en la versión tablet, a por la gafas de maquetadora y a investigar que lo mueve!

Yeah!

**Comment by nasivuela** [comment]
Reabro, que aún hay que ajustar el menú en tablet

**Comment by VaqueroFontenla** [comment]
Toda la razón, no se me habida cargado la imagen de la tablet, al consultar los requisitos.
En un ratete lo arreglo

**Comment by nasivuela** [comment]
![](https://media.giphy.com/media/VarW8M9eEha1y/giphy.gif)
