### ISSUE TITLE
target="_blank" mola, peeeero

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-VaqueroFontenla#7]
Cuidado con dónde lo usamos, en este caso estamos haciendo una demo, como si nuestra web fuera la de Adalab, así que el logo debería llevarnos a la `landing o página principal`. Aquí, que se abra una nueva pestaña interesa menos. Un buen candidato es la página con la politica de privacidad, o una web externa.

**Comment by VaqueroFontenla** [comment]
No entiendo bien esto. Cunado el usuario pulsa en el logo de Adalab, el enlace llega a la página principal de Adalab, como se pedía en el ejercicio.
El uso  del atributo targer="_black" es con la intención de que se abra en otra pestaña ... esto es lo NO recomendable?

**Comment by nasivuela** [comment]
Sorry Loreto, igual esto estaba un poco confuso. En el ejercicio nosotras estamos haciendo la web de Adalab (simplificada y como si no existiera la de verdad ;), así que la home de Adalab es justo lo que hemos maquetado. No se si esto lo aclara, de todas formas es un detalle.

**Comment by VaqueroFontenla** [comment]
Vale.... entiendo. Entonces el tema sería cambiar el enlace y que redireccione a otra página "secundaria", cierto?

**Comment by nasivuela** [comment]
Redireccionaria a la home, que es la página en la que estamos actualmente. En el proyecto veremos como ir desde contacto hacía la home a través del logo.

Solo era un apunte conceptual, el enlace tendría que ser en este caso a la página en la que estamos actualmente.
